# Generated by Django 4.1 on 2022-08-12 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('descritption', models.TextField(blank=True)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('category', models.CharField(choices=[('MOT', 'Motors'), ('FAS', 'Fashion'), ('ELE', 'Electronics'), ('ART', 'Collectibles & Art'), ('HGA', 'Home & Garden'), ('SPO', 'Sporting Goods'), ('TOY', 'Toys'), ('BUS', 'Business & Industrial'), ('MUS', 'Music')], default='MOT', max_length=3)),
                ('image_url', models.URLField(blank=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
